InstRep/api/urls.py
from rest_framework import routers
from django.conf.urls import include, url
from forms.viewset import FormViewSet
from complaints.viewset import ComplaintViewSet
from users.viewset import UserViewSet
from sign_up import sign_up
from form_submit import form_submit
from institution_sign_up import institution_sign_up
from get_file import get_file

router = routers.DefaultRouter()
router.register(r'forms', FormViewSet, 'forms')
router.register(r'complaints', ComplaintViewSet, 'complaints')
router.register(r'users', UserViewSet, 'users')

urlpatterns = [
    url(r'^build_form', 'api.views.build_form'),
    url(r'^sign_up/', sign_up),
    url(r'^form_submit/(?P<form_id>[0-9]+)/', form_submit),
    url(r'^institution_sign_up/', institution_sign_up),
    url(r'^get_file/', get_file),
    url(r'^', include(router.urls)),
]

InstRep/complaints/urls.py
from django.conf.urls import url, patterns

urlpatterns = patterns( 'complaints',
    url(r'^(?P<complaint_id>[0-9]+)/$', 'views.show', name='show'),
    url(r'^(?P<hash_value>\w+)/$', 'views.hash_show', name='hash_show'),
)

InstRep/myapp/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    url(r'^o/', include('oauth2_provider.urls', namespace='oauth2_provider')),
    url(r'^admin/inst_profile', 'myapp.views.inst_profile', name='inst_profile'),
    url(r'^admin/', include(admin.site.urls)),
    url(r'^$', 'myapp.views.home'),
    url(r'^profile', 'users.views.profile', name='profile'),
    url(r'^dashboard', 'users.views.dashboard', name='dashboard'),
    url(r'^submit/(?P<user_id>[0-9]+)$', 'users.views.submit', name='submit'),
    url(r'^accounts/', include('auth.urls')),
    url(r'^forms/', include('forms.urls', namespace="forms")),
    url(r'^complaints/', include('complaints.urls', namespace="complaints")),
    url(r'^upload/(?P<institution_id>[0-9]+)', 'institutions.views.upload', name='upload'),
    url(r'^thanks_for_submission', 'institutions.views.thanks_for_submission', name='thanks_for_submission'),
    url(r'^institutions/leaderboard', 'institutions.views.leaderboard', name='leaderboard'),
    url(r'^api/', include('api.urls')),
    url(r'^api-auth/', include('rest_framework.urls', namespace='rest_framework')),
] 
if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT) 
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

InstRep/complaints/models.py
# -*- coding: utf-8 -*-
from django.db import models
from users.models import User 
from forms.models import Form, Field 
import datetime

COMPLAINT_STATUSES = (
    (0, "Обработва се"),
    (1, "Отхвърлена"),
    (2, "Разрешена")
)

class Complaint(models.Model):
    form = models.ForeignKey(Form, on_delete=models.SET_NULL, null=True, verbose_name="Форма")
    status = models.PositiveSmallIntegerField(choices=COMPLAINT_STATUSES, verbose_name="Статус")
    created_at = models.DateTimeField(auto_now_add=True, verbose_name="Дата")
    updated_at = models.DateTimeField(auto_now=True)
    user = models.ForeignKey(User, null=True, verbose_name="Потребител")
    hash_value = models.CharField(max_length=20, verbose_name="Хеширан код")
    
    def __unicode__(self):
        if self.form:
            return u'Оплакване до %s' % self.form.institution.name
        else:
            return u'Оплакване до изтрита форма. :('

    class Meta:
        verbose_name = 'оплакване'
        verbose_name_plural = 'оплаквания'
    
from django.core.exceptions import ValidationError
class Fill(models.Model):
    complaint = models.ForeignKey(Complaint)
    field_name = models.CharField(max_length=200, verbose_name="Име на полето")
    val = models.CharField(max_length = 200, verbose_name="Стойност на полето", null=True, blank=True)

    class Meta:
        verbose_name = u'поле'
        verbose_name_plural = u'полета'

    def clean(self):
        field = self.complaint.form.field_set.get(name=self.field_name)
        if field.type == 1 or field.type == 2:
            minimum = float('-inf') if field.minimum is None or field.minimum == -1 else field.minimum
            maximum = float('inf') if field.maximum is None or field.maximum == -1 else field.maximum
            if field.validation_type == 3: # number
                if int(self.val) > maximum or int(self.val) < minimum:
                    raise ValidationError("Field %s must be a number in the range %f-%f" % (self.field_name, minimum, maximum))
            else: # regular string
                if len(self.val) > maximum or len(self.val) < minimum:
                    raise ValidationError(u"Field {0} must have length in interval {1}-{2}".format(self.field_name, minimum, maximum))

    def save(self, **kwargs):
        self.clean()
        return super(Fill, self).save(**kwargs)

    def __unicode__(self):
        return u'Поле'

def generate_filename(self, filename):
    url = "files/users/%s/%s" % (self.user.username, filename)
    return url
    
class File(models.Model):
    complaint = models.ForeignKey(Complaint)
    field_name = models.CharField(max_length = 100)
    val = models.FileField(upload_to=generate_filename, blank=True, null=True)
    
class Comment(models.Model):
    complaint = models.ForeignKey(Complaint)
    date = models.DateTimeField(auto_now_add=True)
    text = models.TextField()

    class Meta:
        verbose_name = u'коментар'
        verbose_name_plural = u'коментари'

InstRep/complaints/views.py
# -*- coding: utf-8 -*-
from django.contrib import messages
from django.http.response import Http404
from django.shortcuts import redirect
from django.shortcuts import render
from .models import Complaint, Comment
from .utils import build_context_data
from myapp.utils import validate_request

def show(request, complaint_id):
    validate_request(request, 'GETPOST')
    
    complaint = Complaint.objects.get(id=complaint_id)
    if request.method == 'POST':
        comment_text = request.POST.get('comment_text')
        Comment.objects.create(complaint=complaint, text=comment_text)

    return render(request, 'complaints/show.html', build_context_data(complaint))

def hash_show(request, hash_value):
    complaint = Complaint.objects.get(hash_value=hash_value)
    if request.method == 'POST':
        comment_text = request.POST.get('comment_text')
        Comment.objects.create(complaint=complaint, text=comment_text)

    return render(request, 'complaints/show.html', build_context_data(complaint))

InstRep/complaints/templates/complaints/show.html
{% extends "base.html" %}
{% load user_extras %}
{% load complaint_extras %}
{% block page_title %}Complaint show by hash{% endblock %}
{% block content %}

{% if not user.is_authenticated %}
	<div class="container">
	    <div class="jumbotron">
	        <p>Not being a user, we cannot link the complaint to thy profile.</p>
	        <p>... But fear not!!! Thou shalt be able to useth this link whenever thou wishes to gaze upon thy complaint.</p>
	        <a href="{% url 'complaints:hash_show' complaint.hash_value %}">{{request.get_host}}{% url 'complaints:hash_show' complaint.hash_value %}</a>
	    </div>
	</div>
{% endif %}

<div class="container">
    <div class="jumbotron table-responsive">

    	<table class="table table-hover table-bordered">
            <thead>
                <tr class="dashboard-table-head-size">
                    <th class="text-center col-md-1">ID на жалбата</th>
                    <th class="text-center col-md-2">Институция</th>
                    <th class="text-center col-md-2">Форма</th>
                    <th class="text-center col-md-2">Дата на подаване</th>
                    <th class="text-center col-md-1">Статус</th>
                </tr>
            </thead>
            <tbody>
                <tr class="dashboard-text-size">
                    <td id="align-vert" class="text-center">
                        <a id="blue_background" href="{% url 'complaints:show' complaint.id %}" class="btn btn-primary lab label" role="button">Жалба №{{ complaint.id}}</a>
                    </td>
                    <td id="align-vert" class="text-center">{{complaint.form.institution.name}}</td>
                    <td id="align-vert" class="text-center">{{complaint.form.name}}
                    <td id="align-vert" class="text-center">{{complaint.created_at|date:"G:i d.m.Y"}}</td>
                    <td id="align-vert" class="text-center">
        {% if complaint.status == 2 %}

                        <span id="status" class="label label-success label-as-status">Разрешена</span>
                  {% elif complaint.status == 1 %}

                        <span id="status" class="label label-danger label-as-status">Отхвърлена</span>
                  {% elif complaint.status == 0 %}

                        <span id="status" class="label label-warning label-as-status">Чакаща разглеждане</span>
                  {% endif %}

                    </td>
                </tr>
            </tbody>
        </table>

        <table class="table table-hover table-bordered">
            <thead>
                <tr>
                    <th class="text-center col-md-2">Име на полето</th>
                    <th class="text-center col-md-6">Описание</th>
                </tr>
            </thead>
            <tbody>
	          {% for fill in fills %}
                  {% is_hidden fill as hidden %}
                  {% if not hidden %}
                    <tr>
                        <td class="text-center">{{fill.field_name}}</td>
                        <td class="text-center">{{fill.val}}</td>
                    </tr>
                {% endif %}
			  {% endfor %}

		      {% for file in files %}

                <tr>
                    <td>
                        <a href = "{{file.val.name}}">{{file.field_name}}</a>
                    </td>
                </tr>
			  {% endfor %}

            </tbody>
        </table>
    </div>
    <div class="action-box jumbotron">
        <div class="detailBox">
            <div class="titleBox">
                <label class="dashboard-table-head-size">Коментари и обратна връзка</label>
                <button type="button" class="close" aria-hidden="true">&times;</button>
            </div>
            <div class="actionBox">
                <ul class="commentList">
		  	{% for comment in comments %}
                    <li class="text_color">
                        <div class="commentText">
                            <strong id="comment-size">{{ comment.text }}</strong><br>
                            <span class="date sub-text">{{comment.date|date:"G:i d.m.Y"}}</span>
                        </div>
                    </li>
	         {% endfor %}

                </ul>
                <form class="form-inline" role="form" method="post" action="{{ request.path }}">
                    <div class="form-group">
                        <input class="form-control" type="text" name="comment_text" />
                    </div>
                    <div class="form-group">
                        <button class="btn btn-primary" id="blue_background">Пост</button>
                    </div>
	            {% csrf_token %}

                </form>
            </div>
        </div>
    </div>
    <style>

.detailBox {
    width:90%;
    border:1px solid #bbb;
   	margin-left: 5%;
}
.titleBox {
    background-color:#fdfdfd;
    padding:10px;
}
.titleBox label{
  color:#444;
  margin:0;
  display:inline-block;
}

.commentBox {
    padding:10px;
    border-top:1px dotted #bbb;
}
.commentBox .form-group:first-child, .actionBox .form-group:first-child {
    width:80%;
}
.commentBox .form-group:nth-child(2), .actionBox .form-group:nth-child(2) {
    width:18%;
}
.actionBox .form-group * {
    width:100%;
}
.taskDescription {
    margin-top:10px 0;
}
.commentList {
    padding:0;
    list-style:none;
    overflow:auto;
}
.commentList li {
    margin:0;
    margin-top:10px;
}
.commentList li > div {
    display:table-cell;
}
.commentText p {
    margin:0;
}
.sub-text {
    color:#aaa;
    font-family:verdana;
    font-size:14px;
}
.actionBox {
    border-top:1px dotted #bbb;
    padding:10px;
}
	</style>

{% endblock content %}