InstRep/api/urls.py
from rest_framework import routers
from django.conf.urls import include, url
from forms.viewset import FormViewSet
from complaints.viewset import ComplaintViewSet
from users.viewset import UserViewSet
from sign_up import sign_up
from form_submit import form_submit
from institution_sign_up import institution_sign_up
from get_file import get_file

router = routers.DefaultRouter()
router.register(r'forms', FormViewSet, 'forms')
router.register(r'complaints', ComplaintViewSet, 'complaints')
router.register(r'users', UserViewSet, 'users')

urlpatterns = [
    url(r'^build_form', 'api.views.build_form'),
    url(r'^sign_up/', sign_up),
    url(r'^form_submit/(?P<form_id>[0-9]+)/', form_submit),
    url(r'^institution_sign_up/', institution_sign_up),
    url(r'^get_file/', get_file),
    url(r'^', include(router.urls)),
]

InstRep/forms/urls.py
from django.conf.urls import url, patterns

urlpatterns = patterns( 'forms',
    url(r'^$', 'views.index', name='index'),
    url(r'^(?P<form_id>[0-9]+)/$', 'views.show', name='show'),
    url(r'^(?P<form_id>[0-9]+)/submit/$', 'views.submit', name='submit'),
)

InstRep/myapp/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    url(r'^o/', include('oauth2_provider.urls', namespace='oauth2_provider')),
    url(r'^admin/inst_profile', 'myapp.views.inst_profile', name='inst_profile'),
    url(r'^admin/', include(admin.site.urls)),
    url(r'^$', 'myapp.views.home'),
    url(r'^profile', 'users.views.profile', name='profile'),
    url(r'^dashboard', 'users.views.dashboard', name='dashboard'),
    url(r'^submit/(?P<user_id>[0-9]+)$', 'users.views.submit', name='submit'),
    url(r'^accounts/', include('auth.urls')),
    url(r'^forms/', include('forms.urls', namespace="forms")),
    url(r'^complaints/', include('complaints.urls', namespace="complaints")),
    url(r'^upload/(?P<institution_id>[0-9]+)', 'institutions.views.upload', name='upload'),
    url(r'^thanks_for_submission', 'institutions.views.thanks_for_submission', name='thanks_for_submission'),
    url(r'^institutions/leaderboard', 'institutions.views.leaderboard', name='leaderboard'),
    url(r'^api/', include('api.urls')),
    url(r'^api-auth/', include('rest_framework.urls', namespace='rest_framework')),
] 
if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT) 
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

InstRep/forms/models.py
# -*- coding: utf-8 -*-
from django.db import models
from institutions.models import Institution

FIELD_TYPES = (
    (1, 'Текстово поле'), 
    (2, 'Текст'), 
    (3, 'Падащо поле'),
    (4, 'Бутони за единичен избор'),
    (5, 'Email'),
    (6, 'Файл'),
    (7, 'Кутийка за избор'),
    (8, 'Скрито поле'),
)

AUTOFILL_NAMES = (
    (-1, '-'),
    (0, 'Лично име'), 
    (1, 'Фамилия'), 
    (2, 'Град'), 
    (3, 'Телефон'), 
    (4, 'Email'), 
    (5, 'Адрес'),                  
)

VALIDATION_TYPES = (
    (-1, '-'),
    (0, 'Телефон'), 
    (1, 'Пощенски код'), 
    (2, 'Име'),
    (3, 'Число'),
)

class Form(models.Model):
    institution = models.ForeignKey(Institution)
    name = models.CharField(max_length=150, verbose_name="Име на формата")
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    main_field = models.CharField(max_length=200, null=True, blank=True)
    approved = models.BooleanField(default=False, verbose_name="Одобрена")

    class Meta:
        verbose_name = 'форма'
        verbose_name_plural = 'форми'

    def __unicode__(self):
        return u'%s' % self.name

class Field(models.Model):
    form = models.ForeignKey(Form)
    type = models.PositiveSmallIntegerField(choices = FIELD_TYPES, verbose_name="Тип на полето")
    name = models.CharField(max_length = 100, verbose_name="Име на полето")
    html_name = models.CharField(default="", max_length=50, verbose_name="HTML name атрибут")
    description = models.TextField(blank=True, default="", verbose_name="Описание на полето")
    autofill = models.PositiveSmallIntegerField(choices = AUTOFILL_NAMES, default=-1, \
        verbose_name="Автоматично попълване", \
        help_text="Ако потребителят е попълнил профила си с въпросната информация, полето ще се попълни автоматично." \
    )
    required = models.BooleanField(default=False, verbose_name="Задължително")
    validation_type = models.PositiveSmallIntegerField(choices=VALIDATION_TYPES, default=-1, verbose_name="Тип на валидацията")
    minimum = models.IntegerField(default=-1, blank=True, null=True, verbose_name="Минимална големина")
    maximum = models.IntegerField(default=-1, blank=True, null=True, verbose_name="Максимална големина")
    choose_one = models.PositiveSmallIntegerField(blank=True, default=-1)

    field_order = models.PositiveIntegerField(default=0, db_index=True)

    class Meta:
        verbose_name = u'поле'
        verbose_name_plural = u'полета'
        ordering = ['field_order']
    
class FieldOption(models.Model):
    field = models.ForeignKey(Field)
    option = models.CharField(max_length = 50)

    field_option_order = models.PositiveIntegerField(default=0, db_index=True)

    class Meta:
        verbose_name = u'опция'
        verbose_name_plural = u'опции'
        ordering = ['field_option_order']

InstRep/forms/admin.py
# -*- coding: utf-8 -*-
from django.contrib import admin
from forms.models import Form, Field, FieldOption
from users.models import User
from institutions.models import Institution
from django.core.urlresolvers import reverse
from django.conf.urls import url
from django.shortcuts import redirect, render
from django.contrib import messages
from myapp.utils import validate_request

from django.contrib.admin import TabularInline, StackedInline, site
from super_inlines.admin import SuperInlineModelAdmin, SuperModelAdmin

import re

class FieldOptionInline(SuperInlineModelAdmin, StackedInline):
    model = FieldOption
    extra = 0
    fk_name = "field"

class FieldInline(SuperInlineModelAdmin, StackedInline):
    model = Field
    fk_name="form"
    inlines = [FieldOptionInline]
    exclude = ['choose_one']

    def get_extra(self, request, obj=None, **kwargs):
        # /admin/forms/form/add/
        if re.match(r'/admin/forms/form/add/', request.path):
            return 1
        # /admin/forms/form/37/
        else:
            return 0

class FormAdmin(SuperModelAdmin):
    model = Form
    inlines = [FieldInline]
    list_display = ('name', 'approved')
    list_filter = ('institution','approved')
    actions = ['approve_form']

    def approve_form(self, request, queryset):
        validate_request(request, 'POST')
        queryset.update(approved=True)
    approve_form.short_description = u'Одобри формата'

    def get_actions(self, request):
        validate_request(request, 'GETPOST')
        actions = super(FormAdmin, self).get_actions(request)
        if not request.user.is_superuser:
            del actions['approve_form']
        return actions

    def get_urls(self):
        urls = super(FormAdmin, self).get_urls()
        my_urls = [
            url(r'^(?P<form_id>[0-9]+)/main_field_select', self.main_field_select_view),
        ]
        return my_urls + urls

    def main_field_select_view(self, request, form_id):
        validate_request(request, 'GETPOST')
        form = Form.objects.get(pk=form_id)
        fields = form.field_set.all()
        if request.method == 'POST':
            form.main_field = request.POST.get('main_field_name')
            form.save()
            messages.success(request, 'Successfully created/updated form.')
            return redirect('/admin/forms')
        return render(request, 'admin/forms/form/main_field_select.html', {'form': form, 'fields': fields})

    # Fields in show action
    def get_fields(self, request, obj=None):
        validate_request(request, 'GETPOST')
        if request.user.is_superuser:
            return super(FormAdmin, self).get_fields(request,obj)
        else:
            return ('name',)

    # Where to redirect on object creation
    def response_add(self, request, obj):
        return redirect("/admin/forms/form/%d/main_field_select_view" % obj.id)

    # Where to redirect on change
    def response_change(self, request, obj):
        return redirect("/admin/forms/form/%d/main_field_select_view" % obj.id)

    # Called after clicking "Save" and before saving to the DB
    def save_model(self, request, obj, form, change):
        validate_request(request, 'POST')
        if not request.user.is_superuser:
            obj.institution = Institution.objects.get(user=(User.objects.get(user=request.user)))
        obj.save()

    # Limit what to list in index
    def get_queryset(self, request):
        validate_request(request, 'GETPOST')
        qs = super(FormAdmin, self).get_queryset(request)
        if request.user.is_superuser:
            return qs

        return qs.filter(institution__user=User.objects.get(user=request.user))

    def get_readonly_fields(self, request, obj=None):
        validate_request(request, 'GETPOST')
        if request.user.is_superuser:
            return super(FormAdmin, self).get_readonly_fields(request, obj)
        else:
            return ('institution', 'main_field')

admin.site.register(Form, FormAdmin)

InstRep/forms/apps.py
# -*- coding: utf-8 -*-
from django.apps import AppConfig
import watson

class FormConfig(AppConfig):
    name = 'forms'
    verbose_name = u'Форми'

    def ready(self):
        Form = self.get_model('Form')
        watson.register(Form.objects.filter(approved=True), fields=('name',))

InstRep/forms/serializer.py
import json
from rest_framework import routers, serializers, viewsets
from .models import Form, Field, FieldOption
from institutions.models import Institution
from users.models import User

class FieldOptionSerializer(serializers.ModelSerializer):
    class Meta:
        model = FieldOption
        fields = ('option',)

    def create(self, data, field):
        data['field'] = field
        FieldOption.objects.create(**data)

class FieldSerializer(serializers.ModelSerializer):
    fieldoption_set = FieldOptionSerializer(many=True, read_only=True)
    class Meta:
        model = Field
        exclude = ('field_order', 'form', )

    def create(self, data, form):
        data['form'] = form
        field_options = data.pop('fieldoption_set', None)
        field1 = Field.objects.create(**data)
        if field_options:
            for field_option in field_options:
                FieldOptionSerializer().create(field_option, field1)

    def update(self, data):
        field_options = data.pop('fieldoption_set', None)
        if field_options:
            field = Field.objects.get(pk=data['id'])
            field.fieldoption_set.all().delete() # delete options

            for field_option in field_options: # create new ones
                FieldOptionSerializer().create(field_option, field)

        Field.objects.filter(pk=data['id']).update(**data)

class FormSerializer(serializers.ModelSerializer):
    inst_name = serializers.SerializerMethodField()
    field_set = FieldSerializer(many=True, read_only=True)

    class Meta:
        model = Form
        fields = ('id', 'name', 'inst_name', 'created_at', 'updated_at', 'main_field','field_set', )

    def get_inst_name(self, obj):
        return obj.institution.name

    def create(self, data, institution):
        try:
            data = dict(data.iterlists())
            data['institution'] = institution

            fields = data.pop('field_set', None)
            if fields:
                fields = eval(fields[0])
                form = Form.objects.create(**data)
                for field in fields:
                    FieldSerializer().create(field, form)

            return {'status': 'success'}
        except Exception as e:
            return {'status': 'error', 'error': str(e)}

    def update(self, form_id, data):
        try:
            form = Form.objects.get(pk=form_id)
            for field in form.field_set.all():
                field.delete()
            data = dict(data) # convert QuerySet to dictionary
            fields = data.pop('field_set', None) # returns a unicode string, not a list
            if fields:
                fields = eval(fields[0]) # effectively convert to list
                for field in fields:
                    FieldSerializer().create(field, form)

            # data is {'name': [u'newname']}
            data = {attr: value[0] for attr, value in data.items()} # "flatten" the data
            Form.objects.filter(pk=form_id).update(**data)
            return {'status': 'success'}
        except Exception as e:
            return {'status': 'error', 'error': str(e)}

InstRep/forms/tests.py
from django.test import TestCase
import forms_tests
# Create your tests here.

InstRep/forms/utils.py
import myapp.settings as settings
import os
import watson
from complaints.models import Complaint, File
from forms.models import Form
from institutions.models import Institution
from itertools import chain

def hash_taken(hash_value):
    return len(Complaint.objects.filter(hash_value=hash_value)) > 0

def gen_hash():
    hash_value = os.urandom(10).encode('hex')
    while hash_taken(hash_value):
        hash_value = os.urandom(10).encode('hex')
    return hash_value

def build_form_query_result(query):
    results = []
    institution_search = watson.filter(Institution, query)
    institution_capitalized_search = watson.filter(Institution, query.capitalize())
    institutions = list(chain(institution_search, institution_capitalized_search))

    for institution in institutions:
        for form in institution.form_set.all():
            results.append(form)

    form_search = watson.filter(Form, query)
    form_capitalized_search = watson.filter(Form, query.capitalize())
    forms = list(chain(form_search, form_capitalized_search))

    for form in forms:
        results.append(form)

    return set(results)

def get_path(user, complaint):
    username = user.user.username if user else 'anonymous'
    return "user_uploads/{0}/{1}/".format(username, complaint.id)

def write_to_destination(url, file):
    if not os.path.exists(url):
        os.makedirs('/'.join(url.split('/')[0:-1]))

    destination = open(url, "wb+")
    for chunk in file.chunks():
        destination.write(chunk)
    destination.close()

def handle_files(complaint, files, user):
    for key, file in files:
        new_file = File(complaint=complaint)
        new_file.field_name = key

        name_path = get_path(user, complaint)
        destination_url = settings.MEDIA_ROOT + '/' + name_path + file.name
        write_to_destination(destination_url, file)

        new_file.val.name = settings.MEDIA_URL + name_path + file.name
        new_file.save()

def create_complaint(form, user, post_data, files):
    new_complaint = Complaint.objects.create(
        form=form,
        user=user,
        status=0,
        hash_value=gen_hash()
    )

    for field in form.field_set.all():
        value = post_data.get(field.html_name)
        if value is not None and field.type != 6:
            new_complaint.fill_set.create(field_name=field.name, val=value)

    handle_files(new_complaint, files, user)

    return new_complaint

import ipware.ip
def get_ip(request):
    ip = ipware.ip.get_ip(request)
    if ip is not None:
        return ip
    else:
       return '-Not available-'

def read_file_content(file):
    content = ""
    for chunk in file.chunks():
        content += chunk
    return content

import base64
def files_to_dicts(form_name, files):
    form = Form.objects.get(name=form_name)
    file_fields = form.field_set.filter(type=6)
    dicts = []

    for file_field in file_fields:
        html_name = file_field.html_name
        actual_file = files.get(html_name, None)
        if actual_file:
            dicts.append({html_name: [{'name': actual_file.name, 'content': base64.b64encode(read_file_content(actual_file))}]})
        else:
            dicts.append({html_name: [{'name': '', 'content': ''}]})

    return dicts

InstRep/forms/templates/forms/index.html
{% extends "base.html" %} {% load i18n %}

{% block page_title %}Forms Index{% endblock %}


{% block content %}
	<form method="POST" action="{% url 'forms:index' %}" style="float:right; padding-right:5%">
		{% csrf_token %}
		<input type="text" name="search" placeholder="Търсене..." size="27">
		<a href=""><span class="glyphicon glyphicon-search"></span></a>
	</form>
	<br><br>
	<div class="span2 col-md-8 col-md-offset-2">
	{% if not forms %}
		<p>Все още няма създадени форми! Елате по-късно!</p>
	{% else %}
		{% for form in forms %}
			{% if form.approved %}
				<p class="institution"><a href="{{form.id}}/"><button class="btn btn-default btn-block wrap-institution-list">{{ form.name }} към {{form.institution.name}}</button></a></p>
			{% endif %}
		{% endfor %}
	{% endif %}
	</div>
{% endblock %}

InstRep/forms/templates/forms/show.html
{% extends "base.html" %}

<script> $('.selectpicker').selectpicker();</script>

{% load form_extras %} <!-- Gives switch functionality in templates -->

{% block page_title %}Submit a complaint{% endblock %}

{% block content %}
<div class="container jumbotron text_color" style="padding: 0% 5%;">
  <h2 class="form_header" id="form-title">{{ form.name }}</h2>
  <form method="post" action="{% url 'forms:submit' form.id %}" enctype="multipart/form-data" role="form" id="form">
    {% csrf_token %}
    {% for field in fields %}
    {% if field.type == 8 %} <!-- hidden -->
    	{% if field.required %}
			<input type="hidden" name="{{ field.html_name }}" data-autofill="{{ field.autofill }}" required data-validation="{{ field.validation_type }}" data-minimum="{{ field.minimum }}" data-maximum="{{ field.maximum }}">
		{% else %}
			<input type="hidden" name="{{ field.html_name }}" data-autofill="{{ field.autofill }}" data-validation="{{ field.validation_type }}" data-minimum="{{ field.minimum }}" data-maximum="{{ field.maximum }}">
		{% endif %}
    {% else %}
    <div class="form-group">
	      {% if field.required %}
	      	<label for="{{ field.html_name }}">{{field.name}}: <span style="color:red;">*</span></label>
	      {% else %}
	      	<label for="{{ field.html_name }}">{{field.name}}:</label>
	      {% endif %}
	      <span data-toggle="tooltip" title="{{ field.description }}"></span>
      {% switch field.type %}
	      {% case 2 %} <!-- Textarea -->
		    {% if field.required %}
				<textarea style="resize: none;" class="form-control" id="comment" name="{{field.html_name}}" data-autofill="{{field.autofill}}"  required ></textarea>
			{% else %}
				<textarea style="resize: none;" class="form-control" id="comment" name="{{field.html_name}}" data-autofill="{{field.autofill}}" ></textarea>
			{% endif %}
		  {% case 5 %} <!-- Email -->
		  	{% if field.required %}
	   	    	<input id="login-username" type="email" class="form-control" name="{{field.html_name}}" value="" data-autofill="{{field.autofill}}"  required data-choose-one="{{ field.choose_one }}" data-label="{{ field.name }}">
	       	{% else %}
	       		<input id="login-username" type="email" class="form-control" name="{{field.html_name}}" value="" data-autofill="{{field.autofill}}" data-choose-one="{{ field.choose_one }}" data-label="{{ field.name }}">
	        {% endif %}
	      {% case 3 %} <!-- Select -->
	      	<br>
	      	{% if field.required %}
				<select class="selectpicker btn btn-default dropdown-toggle" data-toggle="dropdown" name="{{field.html_name}}"   required >
			{% else %}
				<select class="selectpicker btn btn-default dropdown-toggle" data-toggle="dropdown" name="{{field.html_name}}" >
			{% endif %}
			{% for option in field.fieldoption_set.all %}
				<option value="{{option.option}}">{{option.option}}</option>
			{% endfor %}
			</select>
	      {% case 4 %} <!-- Radio -->
	      	{% if field.required %}
				{% for option in field.fieldoption_set.all %}
					<br><input type="radio" name="{{field.html_name}}" value="{{option.option}}" required \>{{option.option}}
				{% endfor %}
			{% else %}
				{% for option in field.fieldoption_set.all %}
					<br><input type="radio" name="{{field.html_name}}" value="{{option.option}}" \>{{option.option}}
				{% endfor %}
				<br><br>
			{% endif %}
		  {% case 7 %} <!-- Checkbox -->
		  	<input type="checkbox" name="{{field.name}}" ><br>
		  {% case 6 %} <!-- File -->
		  	<br>
		  	{% if field.required %}
				<span class="btn btn-default btn-file"><input type="file" name="{{field.html_name}}" data-autofill={{field.autofill}} required ></span>
			{% else %}
				<span class="btn btn-default btn-file"><input type="file" name="{{field.html_name}}" data-autofill={{field.autofill}} ></span>
			{% endif %}
		  {% else %} <!-- Text field-->
			<span class="help-block"></span>
			{% if field.required %}
				<input type="text" class="form-control checkbox-inline" name="{{field.html_name}}" data-autofill={{field.autofill}} required data-validation="{{ field.validation_type }}" data-minimum="{{ field.minimum }}" data-maximum="{{ field.maximum }}" data-choose-one="{{ field.choose_one }}" data-label="{{ field.name }}">
			{% else %}
				<input type="text" class="form-control checkbox-inline" name="{{field.html_name}}" data-autofill={{field.autofill}} data-validation="{{ field.validation_type }}" data-minimum="{{ field.minimum }}" data-maximum="{{ field.maximum }}" data-choose-one="{{ field.choose_one }}" data-label="{{ field.name }}"> <!-- label is for choose_one alert message-->
			{% endif %}
      	{% endswitch %}
      </div>
      	<br><br>
      {% endif %}
      {% endfor %}
      <button type="submit" class="btn btn-primary" id="blue_background">Подай</button>
  </form>
</div>

  <script src="/static/js/forms_show.js"></script>
	<script>
		// Auto-fill names
		var default_fields = new Array(
			"{{ custom_user.first_name }}",
			"{{ custom_user.last_name }}",
			"{{ custom_user.city }}",
			"{{ custom_user.phone }}",
			"{{ custom_user.email }}",
			"{{ custom_user.address }}"
		);
		var fields = document.getElementsByClassName('form-control');
		for (var i = 0; i < fields.length; ++i) {
			var curr_autofill = fields[i].getAttribute("data-autofill");
			if(curr_autofill != -1){
				var fill = default_fields[curr_autofill];
				if(fill.trim() == "None") fill = '';
				if(fields[i].tagName == "TEXTAREA")
					fields[i].value = fill.replace(/&quot;/g,"\"").replace(/&#39;/g, "\'");
				else
					fields[i].setAttribute('value', fill.replace(/&quot;/g,"\"").replace(/&#39;/g, "\'"));
			}
		}

		// Fill hidden fields accordingly for Inspekciq po truda's form
		$(document).ready(function() {
			if($("h2#form-title").text() == "Сигнал за нарушение на разпоредбите на трудовото законодателство и ЗДСл") {
				$("input[type=\"hidden\"][name=\"lang_id\"").attr("value", "1");
				$("input[type=\"hidden\"][name=\"sender_ip\"").attr("value", "{{ ip }}");
				$("input[type=\"hidden\"][name=\"cookie\"").attr("value", $("{% csrf_token %}").attr("value"));
			}
		});
	</script>
{% endblock content %}