InstRep/api/urls.py
from rest_framework import routers
from django.conf.urls import include, url
from forms.viewset import FormViewSet
from complaints.viewset import ComplaintViewSet
from users.viewset import UserViewSet
from sign_up import sign_up
from form_submit import form_submit
from institution_sign_up import institution_sign_up
from get_file import get_file

router = routers.DefaultRouter()
router.register(r'forms', FormViewSet, 'forms')
router.register(r'complaints', ComplaintViewSet, 'complaints')
router.register(r'users', UserViewSet, 'users')

urlpatterns = [
    url(r'^build_form', 'api.views.build_form'),
    url(r'^sign_up/', sign_up),
    url(r'^form_submit/(?P<form_id>[0-9]+)/', form_submit),
    url(r'^institution_sign_up/', institution_sign_up),
    url(r'^get_file/', get_file),
    url(r'^', include(router.urls)),
]

InstRep/myapp/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    url(r'^o/', include('oauth2_provider.urls', namespace='oauth2_provider')),
    url(r'^admin/inst_profile', 'myapp.views.inst_profile', name='inst_profile'),
    url(r'^admin/', include(admin.site.urls)),
    url(r'^$', 'myapp.views.home'),
    url(r'^profile', 'users.views.profile', name='profile'),
    url(r'^dashboard', 'users.views.dashboard', name='dashboard'),
    url(r'^submit/(?P<user_id>[0-9]+)$', 'users.views.submit', name='submit'),
    url(r'^accounts/', include('auth.urls')),
    url(r'^forms/', include('forms.urls', namespace="forms")),
    url(r'^complaints/', include('complaints.urls', namespace="complaints")),
    url(r'^upload/(?P<institution_id>[0-9]+)', 'institutions.views.upload', name='upload'),
    url(r'^thanks_for_submission', 'institutions.views.thanks_for_submission', name='thanks_for_submission'),
    url(r'^institutions/leaderboard', 'institutions.views.leaderboard', name='leaderboard'),
    url(r'^api/', include('api.urls')),
    url(r'^api-auth/', include('rest_framework.urls', namespace='rest_framework')),
] 
if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT) 
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

InstRep/institutions/models.py
# -*- coding: utf-8 -*-
from __future__ import division
from django.db import models
from django.core.exceptions import ValidationError
from users.models import User
import datetime
from datetime import timedelta
import watson
from django.utils.version import get_complete_version

INST_STATUSES = (
    (0,'inactive'),
    (1,'pending'),
    (2,'active'),
)

def generate_filename(self, filename):
    return "%s/%s" % (self.name, filename)

class Institution(models.Model):
    name = models.CharField(max_length=200)
    user = models.ForeignKey(User)
    upload = models.FileField(upload_to=generate_filename)
    status = models.PositiveSmallIntegerField(choices=INST_STATUSES)
    notified = models.BooleanField(default=False)
    
    class Meta:
        verbose_name = u'институция'
        verbose_name_plural = u'институции'

    def get_status(self):
        return INST_STATUSES[self.status][1]

    def file_link(self):
        if self.upload:
            return "<a href='%s'>download</a>" % (self.upload.url,)
        else:
            return "No attachment"
    
    def __unicode__(self):
        return u'%s' % self.name
    
    def get_total_complaints(self):
        total_complaints = 0
        since = datetime.date.today() - timedelta(days=30)
        for form in self.form_set.all():
            total_complaints += form.complaint_set.filter(created_at__range=[since, datetime.date.today()]).count()
        return total_complaints
    
    def get_complaints_count_by_status(self, seeked_status):
        forms = self.form_set.all()
        pc_count = 0
        since = datetime.date.today() - timedelta(days=30)
        for form in forms:
            pc_count += form.complaint_set.filter(status=seeked_status, created_at__range=[since, datetime.date.today()]).count()
        return pc_count
    
    def get_pending_complaints_count(self):
        return self.get_complaints_count_by_status(0)
    
    def get_rejected_complaints_count(self):
        return self.get_complaints_count_by_status(1)
    
    def get_resolved_complaints_count(self):
        return self.get_complaints_count_by_status(2)
    
    def get_seeked_complaints_percentage(self, seeked_status):
        total_complaints = self.get_total_complaints()
        seeked_status_complaints = self.get_complaints_count_by_status(seeked_status)
        if(total_complaints):
            return ((seeked_status_complaints*100) / total_complaints)
        else:
            return 0
        
    def get_pending_complaints_percentage(self):
        return self.get_seeked_complaints_percentage(0)
    
    def get_rejected_complaints_percentage(self):
        return self.get_seeked_complaints_percentage(1)
    
    def get_resolved_complaints_percentage(self):
        return self.get_seeked_complaints_percentage(2)
    
    def save(self, **kwargs):
        self.clean()
        if self.user.permission_level == 2:
            self.user.user.is_staff = True
        return super(Institution, self).save(**kwargs)
    
    def clean(self):
        super(Institution, self).clean()
        if self.user.permission_level != 2:
            raise ValidationError('The user\'s permission level must be \'institution\'')

    file_link.allow_tags = True

# delete user associated with institution when deleting an institution - reverse cascading
from django.db.models.signals import post_delete
def delete_reverse(sender, **kwargs):
    user = kwargs['instance'].user
    if user:
        django_builtin_user = user.user
        django_builtin_user.delete()
        user.delete()
post_delete.connect(delete_reverse, sender=Institution)

InstRep/institutions/forms.py
# -*- coding: utf-8 -*-
from django import forms
from django.core.exceptions import ValidationError
from django.forms import ModelForm
from institutions.models import Institution

class DocumentForm(forms.Form):
    docfile = forms.FileField(
        label='Select a file'
    )

class InstitutionProfileForm(forms.Form):
    inst_name = forms.CharField(max_length=200, label="Име на институцията")
    city = forms.CharField(max_length=30, label="Град")
    phone = forms.CharField(max_length=12, label="Телефон")
    notified = forms.BooleanField(required=False, label="Желаете ли да получавате ежедневен email със сигналите за деня?")

class InstitutionForm(forms.ModelForm):
    class Meta:
        model = Institution
        exclude = []
    
    def clean_user(self):
        user = self.cleaned_data['user']
        i = Institution.objects.filter(user=user)
        if len(i) == 1 and i[0].name == self.cleaned_data['name']:
        	return user
        if len(i) > 0:
            raise ValidationError("The user is already linked to another institution.")
        return user

InstRep/institutions/views.py
from django.core.urlresolvers import reverse
from django.http import HttpResponseRedirect
from django.http.response import Http404
from django.shortcuts import redirect, render, render_to_response
from django.template import RequestContext

from institutions.models import Institution
from institutions.forms import DocumentForm
from myapp.utils import validate_request

def upload(request, institution_id):
    validate_request(request, 'GETPOST')
    if request.method == 'POST':
        try:
            inst = Institution.objects.get(pk=institution_id)
        except:
            raise Http404
        form = DocumentForm(request.POST, request.FILES)
        if form.is_valid():
            inst.upload = request.FILES['docfile']
            inst.status = 1
            inst.save()
            return redirect('thanks_for_submission')
            
    else:
        form = DocumentForm()
        
    return render_to_response(
        'institutions/upload.html',
        {'form': form, "institution_id": institution_id},
        context_instance=RequestContext(request)
    )

def thanks_for_submission(request):
    validate_request(request, 'GET')
    return render(request, 'institutions/thanks_for_submission.html')

def leaderboard(request):
    validate_request(request, 'GET')
    institutions = Institution.objects.filter(status=2)
    least_active_institutions = sorted(institutions, key = lambda x: x.get_pending_complaints_percentage())
    most_active_institutions = sorted(institutions, key = lambda x: x.get_pending_complaints_percentage(), reverse = True)
    most_resolving_institutions = sorted(institutions, key = lambda x: x.get_resolved_complaints_count(), reverse = True)
    most_rejecting_institutions = sorted(institutions, key = lambda x: x.get_rejected_complaints_count(), reverse = True)
    return render(request, 'institutions/leaderboard.html', 
        {'least_active_institutions': least_active_institutions, 'most_active_institutions': most_active_institutions,
         'most_resolving_institutions': most_resolving_institutions, 'most_rejecting_institutions': most_rejecting_institutions}
    )

InstRep/institutions/templates/institutions/leaderboard.html
{% extends "base.html" %} {% load i18n %} 

{% block page_title %}Insitutions leaderboard{% endblock %}

{% block content %}
<div class="container">
	<ul class="nav nav-tabs">
	    <li class="active"><a data-toggle="tab" href="#least-active">Най-неактивни</a></li>
	    <li><a data-toggle="tab" href="#most-active">Най-активни</a></li>
	    <li><a data-toggle="tab" href="#most-resolving">Най-много решени молби</a></li>
	    <li><a data-toggle="tab" href="#most-rejecting">Най-много отхвърлени</a></li>
	</ul>
	<br><br>
	<div class="tab-content">
		<div id="least-active" class="tab-pane fade in active">{% for institution in least_active_institutions %}{% include 'inst_render.html' %}{% endfor %}</div>
		<div id="most-active" class="tab-pane fade">{% for institution in most_active_institutions %}{% include 'inst_render.html' %}{% endfor %}</div>
		<div id="most-resolving" class="tab-pane fade">{% for institution in most_resolving_institutions %}{% include 'inst_render.html' %}{% endfor %}</div>
		<div id="most-rejecting" class="tab-pane fade">{% for institution in most_rejecting_institutions %}{% include 'inst_render.html' %}{% endfor %}</div>
		</div>
	</div> 
</div>
{% endblock %}

InstRep/institutions/templates/institutions/thanks_for_submission.html
{% extends "base.html" %} {% load i18n %}

{% block page_title %}Благодаря за регистрацията{% endblock %}

{% block content %}

<div class="container">
    <div class="jumbotron">
        <p style="text-align:center">Вашият документ ще бъде разгледан възможно най-скоро!</p>
    </div>
</div>

{% endblock %}

InstRep/institutions/templates/institutions/upload.html
{% extends "base.html" %} {% load i18n %}
{% block page_title %}Качване{% endblock %}
{% block content %}
<div class="container">
	<div class="jumbotron">
		<p style="text-align:center">Прикачете копие от документ, който Ви удостоверява като институция.<br> Документът ще бъде разгледан от системния администратор възможно най-скоро</p>
		<br>
		<br>
		<br>
		<div style="padding-left:40%">
			<form action="{% url "upload" institution_id %}" method="post" enctype="multipart/form-data">
			{% csrf_token %}
			<div style="position:relative">
				<p>{{ form.non_field_errors }}</p>
				<p>{{ form.docfile.errors }}</p>
				<a class='btn btn-default' href='javascript:;' style="width:25%">
					<em >Избери файл...</em>
					<input id="id_docfile" name="docfile" type="file" style='position:absolute;z-index:2;top:0;left:0;filter: alpha(opacity=0);-ms-filter:"progid:DXImageTransform.Microsoft.Alpha(Opacity=0)";opacity:0;background-color:transparent;color:transparent;' name="file_source" size="40"  onchange='$("#upload-file-info").html($(this).val());'>
				</a>
				&nbsp;
				<span class='label label-info' id="upload-file-info"></span>
			</div>
			<br>
				<input type="submit" value="Прикачи" class="btn btn-info" id="blue_background" style="width:25%"/>
			</form>
		</div>
	</div>
</div>
{% endblock %}